CREATE TABLE IF NOT EXISTS lecturer
(
    id               SERIAL PRIMARY KEY,
    chair_id         INTEGER NOT NULL REFERENCES chair (id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES "user" (id) ON DELETE CASCADE
);