jwt:
  issuer: 'cactuscatoo@gmail.com'
  signingKey: 'XBzE8HfMcQfTjWnZr4u7w1zEC2F4JaNdRgUkXp2s5v8yqAED7G5KbPeShVmYq3t6UkXp2s5v8yqAED7G5KbPeShVmYq3t6'
  aTokenDuration: 30
  aLongTokenDuration: 1440

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dplm_db
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: false
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size: 500
      order_inserts: true