version: "3.3"

services:

  nginx:
    container_name: "diploma_nginx"
    build:
      context: "."
      dockerfile: "./docker/nginx/Dockerfile"
    restart: "always"
    volumes:
      - "./docker/nginx/config.conf:/etc/nginx/conf.d/diploma.conf"
    network_mode: "host"

  postgres:
    container_name: "diploma_db"
    image: "postgres:9.6-alpine"
    restart: "always"
    environment:
      POSTGRES_DB: "dplm_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  postfix:
    container_name: "diploma_postfix"
    image: "tozd/postfix"
    ports:
      - "25:25"
      - "587:587"
    restart: "always"
    network_mode: "host"
    environment:
      - "MAILNAME=scheduler.wip"
      - "MY_NETWORKS=127.0.0.0/8"
      - "ROOT_ALIAS=admin@scheduler.wip"
      - "MY_DESTINATION=scheduler.wip, mail.scheduler.wip, localhost.localdomain, localhost"
