version: "3.3"

services:

  nginx:
    container_name: "dimploma_nginx"
    build:
      context: "."
      dockerfile: "./nginx/Dockerfile"
    restart: "always"
    volumes:
      - "./nginx/config.conf:/etc/nginx/conf.d/diploma.conf"
    network_mode: "host"

  postgres:
    container_name: "diploma_db"
    image: "postgres:9.6-alpine"
    restart: "always"
    environment:
      POSTGRES_DB: "dplm_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

